"""Generate a starter Jenkinsfile + job XML for a new pipeline.

Does NOT contact Jenkins. Writes two local files for review, then prints the
exact upsert_job.py command to apply them once you're happy with the
contents.

Two source modes:
    --source scm     (default) — Pipeline script from SCM (recommended)
    --source inline             — Inline pipeline script baked into the job XML

Examples:
    # SCM-backed (default): Jenkinsfile lives in the repo
    python init_pipeline.py my-team-test \\
        --scm-url git@github.com:org/repo.git \\
        --scm-credential my-git-cred \\
        --scm-branch '*/main' \\
        --script-path ci/Jenkinsfile

    # Inline: starter Jenkinsfile embedded directly in the job XML
    python init_pipeline.py quick-prototype --source inline
"""
from __future__ import annotations

import argparse
import re
import sys
import xml.sax.saxutils as saxutils
from pathlib import Path


SCRIPTS_DIR = Path(__file__).resolve().parent
TEMPLATES_DIR = SCRIPTS_DIR / "templates"


def render(template_name: str, vars_: dict[str, str]) -> str:
    text = (TEMPLATES_DIR / template_name).read_text(encoding="utf-8")
    for key, val in vars_.items():
        text = text.replace("{{" + key + "}}", val)
    leftover = re.findall(r"\{\{[A-Z_]+\}\}", text)
    if leftover:
        sys.exit(f"unfilled placeholders in {template_name}: {sorted(set(leftover))}")
    return text


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("name", help="pipeline / job name")
    p.add_argument("--source", choices=["scm", "inline"], default="scm",
                   help="how the pipeline script is delivered (default: scm)")
    p.add_argument("--output-dir", default=".",
                   help="directory to write the generated files into (default: cwd)")
    p.add_argument("--description", default="",
                   help="job description shown in the Jenkins UI")
    p.add_argument("--scm-url", default="",
                   help="git URL (required if --source scm)")
    p.add_argument("--scm-credential", default="",
                   help="Jenkins credential id for the git URL (required if --source scm)")
    p.add_argument("--scm-branch", default="*/main",
                   help="branch spec, e.g. */main or */ci/foo (default: */main)")
    p.add_argument("--script-path", default="Jenkinsfile",
                   help="path to the Jenkinsfile inside the repo (default: Jenkinsfile)")
    args = p.parse_args(argv)

    out_dir = Path(args.output_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    desc = args.description or f"Pipeline {args.name} (generated by init_pipeline)"
    desc_xml = saxutils.escape(desc)

    if args.source == "scm":
        if not args.scm_url or not args.scm_credential:
            sys.exit("--scm-url and --scm-credential are required when --source scm")
        # Always write a starter Jenkinsfile next to the job XML so reviewers
        # see what the script path will resolve to. Operator can either move
        # it into the repo at <scriptPath> or use a different file there.
        jenkinsfile = render("Jenkinsfile.declarative.tpl", {"NAME": args.name})
        (out_dir / "Jenkinsfile").write_text(jenkinsfile, encoding="utf-8")
        xml = render("job-pipeline-scm.xml.tpl", {
            "DESCRIPTION": desc_xml,
            "SCM_URL": saxutils.escape(args.scm_url),
            "SCM_CREDENTIAL": saxutils.escape(args.scm_credential),
            "SCM_BRANCH": saxutils.escape(args.scm_branch),
            "SCRIPT_PATH": saxutils.escape(args.script_path),
        })
    else:  # inline
        jenkinsfile = render("Jenkinsfile.declarative.tpl", {"NAME": args.name})
        (out_dir / "Jenkinsfile").write_text(jenkinsfile, encoding="utf-8")
        xml = render("job-pipeline-inline.xml.tpl", {
            "DESCRIPTION": desc_xml,
            "INLINE_SCRIPT": saxutils.escape(jenkinsfile),
        })

    job_xml_path = out_dir / f"{args.name}.job.xml"
    job_xml_path.write_text(xml, encoding="utf-8")

    print(f"wrote {out_dir / 'Jenkinsfile'} ({len(jenkinsfile)} bytes)")
    print(f"wrote {job_xml_path} ({len(xml)} bytes)")
    print()
    print("next steps:")
    print("  1. Review the generated Jenkinsfile and replace the TODO stages.")
    if args.source == "scm":
        print(f"  2. Commit the Jenkinsfile to {args.scm_url} at path {args.script_path}.")
        print("  3. Apply the job to Jenkins:")
    else:
        print("  2. Apply the job to Jenkins:")
    print(f"     python {SCRIPTS_DIR / 'upsert_job.py'} {args.name} {job_xml_path}")
    print("  Then smoke-test:")
    print(f"     python {SCRIPTS_DIR / 'trigger_build.py'} {args.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
